// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dqvzmlfcmztvqlwykjov.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRxdnptbGZjbXp0dnFsd3lram92Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgzNjg3MzQsImV4cCI6MjA4Mzk0NDczNH0.ZDJljNlH-9RsTEAh85dsDAssGMpvlQiNjxekdN5gCUo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});